###getAll developers
GET https://cse-341-project2-01q7.onrender.com/developers

###getSingle by id
GET https://cse-341-project2-01q7.onrender.com/developers/6928cfee59491059eab5bf47


### createDeveloper
POST https://cse-341-project2-01q7.onrender.com/developers HTTP/1.1
Content-Type: application/json

{
  "id": "dev003",
  "name": "Stanley Bezoz",
  "email": "stbezoz_dev@gmail.com",
  "photos": [
    { "id": "1", "name": "headshot" }
  ],
  "projects": [
    {
      "id": "proj001",
      "name": "Portfolio Website4",
      "url": "https://mdesign.it.com",
      "photos": [
        { "id": "img001", "name": "portfolio-cover.png" },
        { "id": "img002", "name": "screenshot-homepage.jpg" }
      ]
    }
  ]
}

### updateDeveloper
PUT https://cse-341-project2-01q7.onrender.com/developers/692d7e3133069074462639e4 HTTP/1.1
Content-Type: application/json

{
  "id": "dev008",
  "name": "Stanley Bezoz",
  "email": "stbezoz_dev@gmail.com",
  "photos": [
    { "id": "1", "name": "headshot" },
    { "id": "2", "name": "fullshot" }
  ],
  "projects": [
    {
      "id": "proj001",
      "name": "Portfolio Website3",
      "url": "https://example3.com",
      "photos": [
        { "id": "img001", "name": "portfolio-cover.png" },
        { "id": "img002", "name": "screenshot-homepage.jpg" }
      ]
    }
  ]
}


### deleteDeveloper by ID
DELETE https://cse-341-project2-01q7.onrender.com/developers/692d7e3133069074462639e4 HTTP/1.1



### getAll locations 
GET https://cse-341-project2-01q7.onrender.com/locations 

### getSingle location 
GET https://cse-341-project2-01q7.onrender.com/locations/692ca15d7a3a006b5e269cf5


### createLocation
POST https://cse-341-project2-01q7.onrender.com/locations 
Content-Type: application/json

{
  "city": "Abuja",
  "state": "FCT",
  "country": "Nigeria",
  "flag": "nigeria-big-flag.png",
  "photo": "nigeria-landscape.jpg",
  "continent": "Africa",
  "dialCode": "234",
  "currency": "Naira",
  "language": "English"
}


### createLocation\
PUT https://cse-341-project2-01q7.onrender.com/locations/692d7ef633069074462639e5 HTTP/1.1
Content-Type: application/json

{
  "city": "Abuja",
  "state": "FCT",
  "country": "Nigeria",
  "flag": "nigerian-big-flag.png",
  "photo": "nigeria-landscape.jpg",
  "continent": "Africa",
  "dialCode": "234",
  "currency": "Naira",
  "language": "English"
}

### createLocation 
DELETE https://cse-341-project2-01q7.onrender.com/locations/692d7ef633069074462639e5