###getAll developers
GET https://cse-341-project2-01q7.onrender.com/developers

###getSingle by id
GET https://cse-341-project2-01q7.onrender.com/developers/6928cfee59491059eab5bf47


### createDeveloper
POST https://cse-341-project2-01q7.onrender.com/developers HTTP/1.1
Content-Type: application/json

{
  "id": "dev003",
  "name": "Silvia Glory",
  "email": "silviadev@gmail.com",
  "photos": [
    { "id": "1", "name": "headshot" }
  ],
  "projects": [
    {
      "id": "proj001",
      "name": "Portfolio Website4",
      "url": "https://example4.com",
      "photos": [
        { "id": "img001", "name": "portfolio-cover.jpg" },
        { "id": "img002", "name": "screenshot-homepage.jpg" }
      ]
    }
  ]
}

### updateDeveloper
PUT https://cse-341-project2-01q7.onrender.com/developers/6928cfee59491059eab5bf47 HTTP/1.1
Content-Type: application/json

{
  "id": "dev003",
  "name": "Uchendu Emerie",
  "email": "emerieuche@gmail.com",
  "photos": [
    { "id": "1", "name": "headshot" },
    { "id": "2", "name": "fullshot" }
  ],
  "projects": [
    {
      "id": "proj001",
      "name": "Portfolio Website3",
      "url": "https://example3.com",
      "photos": [
        { "id": "img001", "name": "portfolio-cover.jpg" },
        { "id": "img002", "name": "screenshot-homepage.jpg" }
      ]
    }
  ]
}


### deleteDeveloper by ID
DELETE https://cse-341-project2-01q7.onrender.com/developers/692a98e40522fd3bd7d4e03b HTTP/1.1